//! Hidden schema types for ComfyUI v3 nodes.
use pyo3::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt;

/// Enumerator for requesting hidden variables in nodes.
///
/// In Python this is an enum-like `Hidden` value such as
/// `Hidden.PROMPT`, `Hidden.UNIQUE_ID`, `Hidden.EXTRA_PNGINFO`, etc.
#[pyclass(from_py_object)]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum Hidden {
    /// UNIQUE_ID is the unique identifier of the node, and matches the id property of the node on
    /// the client side. It is commonly used in client-server communications (see messages).
    UNIQUE_ID,

    /// PROMPT is the complete prompt sent by the client to the server. See the prompt object for
    /// a full description.
    PROMPT,

    /// EXTRA_PNGINFO is a dictionary that will be copied into the metadata of any .png files saved.
    /// Custom nodes can store additional information in this dictionary for saving (or as a way to
    /// communicate with a downstream node).
    EXTRA_PNGINFO,

    /// DYNPROMPT is an instance of comfy_execution.graph.DynamicPrompt. It differs from PROMPT in
    /// that it may mutate during the course of execution in response to Node Expansion.
    DYNPROMPT,

    /// AUTH_TOKEN_COMFY_ORG is a token acquired from signing into a ComfyOrg account on frontend.
    AUTH_TOKEN_COMFY_ORG,

    /// API_KEY_COMFY_ORG is an API Key generated by ComfyOrg that allows skipping signing into a
    /// ComfyOrg account on frontend.
    API_KEY_COMFY_ORG,
}

impl fmt::Display for Hidden {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Hidden::UNIQUE_ID => write!(f, "UNIQUE_ID"),
            Hidden::PROMPT => write!(f, "PROMPT"),
            Hidden::EXTRA_PNGINFO => write!(f, "EXTRA_PNGINFO"),
            Hidden::DYNPROMPT => write!(f, "DYNPROMPT"),
            Hidden::AUTH_TOKEN_COMFY_ORG => write!(f, "AUTH_TOKEN_COMFY_ORG"),
            Hidden::API_KEY_COMFY_ORG => write!(f, "API_KEY_COMFY_ORG"),
        }
    }
}
