//! Hidden schema types for ComfyUI v3 nodes.
use pyo3::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt;

/// Enumerator for requesting hidden variables in nodes.
///
/// In Python this is an enum-like `Hidden` value such as
/// `Hidden.PROMPT`, `Hidden.UNIQUE_ID`, `Hidden.EXTRA_PNGINFO`, etc.
#[pyclass(from_py_object)]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum Hidden {
    /// UNIQUE_ID is the unique identifier of the node, and matches the id property of the node on
    /// the client side. It is commonly used in client-server communications (see messages).
    UNIQUE_ID,

    /// PROMPT is the complete prompt sent by the client to the server. See the prompt object for
    /// a full description.
    PROMPT,

    /// EXTRA_PNGINFO is a dictionary that will be copied into the metadata of any .png files saved.
    /// Custom nodes can store additional information in this dictionary for saving (or as a way to
    /// communicate with a downstream node).
    EXTRA_PNGINFO,

    /// DYNPROMPT is an instance of comfy_execution.graph.DynamicPrompt. It differs from PROMPT in
    /// that it may mutate during the course of execution in response to Node Expansion.
    DYNPROMPT,

    /// AUTH_TOKEN_COMFY_ORG is a token acquired from signing into a ComfyOrg account on frontend.
    AUTH_TOKEN_COMFY_ORG,

    /// API_KEY_COMFY_ORG is an API Key generated by ComfyOrg that allows skipping signing into a
    /// ComfyOrg account on frontend.
    API_KEY_COMFY_ORG,
}

impl Hidden {
    /// 将 Rust 的 Hidden 枚举转换为 Python 的 io.Hidden 枚举成员
    pub fn to_py_obj<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        // 1. 导入 comfy_api.latest.io 模块
        let io_module = py.import("comfy_api.latest")?.getattr("io")?;

        // 2. 获取 io.Hidden 枚举类
        let hidden_enum = io_module.getattr("Hidden")?;

        // 3. 根据 Rust 的枚举变体，获取对应的 Python 枚举成员属性
        let member_name = match self {
            Hidden::UNIQUE_ID => "unique_id",
            Hidden::EXTRA_PNGINFO => "extra_pnginfo",
            Hidden::PROMPT => "prompt",
            Hidden::DYNPROMPT => "dynprompt",
            Hidden::AUTH_TOKEN_COMFY_ORG => "auth_token_comfy_org",
            Hidden::API_KEY_COMFY_ORG => "api_key_comfy_org",
        };

        hidden_enum.getattr(member_name)
    }
}

impl fmt::Display for Hidden {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Hidden::UNIQUE_ID => write!(f, "unique_id"),
            Hidden::PROMPT => write!(f, "prompt"),
            Hidden::EXTRA_PNGINFO => write!(f, "extra_pnginfo"),
            Hidden::DYNPROMPT => write!(f, "dynprompt"),
            Hidden::AUTH_TOKEN_COMFY_ORG => write!(f, "auth_token_comfy_org"),
            Hidden::API_KEY_COMFY_ORG => write!(f, "api_key_comfy_org"),
        }
    }
}
